config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get "documents/query"

  get "documents/index"

  get "documents/create"

  get "documents/show"

  get "documents/:id/relationship_diagram", to: "documents#relationship_diagram", as: "relationship_diagram"

  get "documents/:id/knowledge_diagram", to: "documents#knowledge_diagram", as: "knowledge_diagram"

  get "documents/:id/entity_tree_map", to: "documents#entity_tree_map", as: "entity_tree_map"

  get "documents/total_relationship_diagram"

  get "documents/total_knowledge_diagram"

  get "documents/total_entity_tree_map"

  resources :documents

  resources :users, only: [:update]

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'

  get 'search' => 'documents#search'

  get 'Raven' => 'welcome#index'

  root to: 'welcome#index'

end

app/models/action.rb
class Action < ActiveRecord::Base
  belongs_to :relation
end

app/models/concept.rb
class Concept < ActiveRecord::Base
  belongs_to :document, touch: true
end

app/models/document.rb
class Document < ActiveRecord::Base
    belongs_to :user, touch: true
    has_many :keywords, as: :keywordable
    has_many :entities, as: :entityable
    has_many :concepts
    has_many :relations
    has_one :sentiment, as: :sentimentable

    

    default_scope { order('created_at DESC') }
end

app/models/entity.rb
class Entity < ActiveRecord::Base
  belongs_to :entityable, polymorphic: true
  belongs_to :document, touch: true
  has_one :sentiment, as: :sentimentable
 end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  belongs_to :document, touch: true
  belongs_to :keywordable, polymorphic: true
  has_one :sentiment, as: :sentimentable
  
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :document, touch: true
  has_many :actions
  has_many :relation_objects
  has_many :keywords, as: :keywordable
  has_many :entities, as: :entityable
end

app/models/relation_object.rb
class RelationObject < ActiveRecord::Base
  belongs_to :relation
  has_one :sentiment, as: :sentimentable
  has_many :keywords, as: :keywordable
  has_many :entities, as: :entityable
  
end

app/models/sentiment.rb
class Sentiment < ActiveRecord::Base
  belongs_to :sentimentable, polymorphic: true
  belongs_to :relation_object
  belongs_to :document
  belongs_to :entity
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  has_many :documents
  mount_uploader :avatar, AvatarUploader


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end

   helper_method :current_user
end

app/controllers/documents_controller.rb
require 'alchemyapi_ruby/alchemyapi'
require 'json'

class DocumentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @documents = Document.all
  end

  def show
    @document = Document.find(params[:id])
    @concepts = @document.concepts
    @entities = @document.entities
    @keywords = @document.keywords
    @relations = @document.relations
  end

  def create
    alchemy_api_parser = AlchemyapiParser.new(params, current_user)
    alchemy_api_parser.call

    if alchemy_api_parser.successful?
      flash[:notice] = "Input was successfully analyzed and persisted."
    else
      flash[:error] = "There was a problem analyzing your input. Please try again."
    end
    redirect_to documents_index_path
  end

  def relationship_diagram
    @document = Document.find(params[:id])
    @entities = @document.entities
    @relations = @document.relations
  end

  def total_relationship_diagram
    @document = Document.all
  end

  def knowledge_diagram
    @document = Document.find(params[:id])
    @entities = @document.entities
    @relations = @document.relations
  end

  def total_knowledge_diagram
    @document = Document.all
  end

  def entity_tree_map
    @document = Document.find(params[:id])
    @entities = @document.entities
    @relations = @document.relations
  end

  def total_entity_tree_map
    @document = Document.all
  end

  def destroy
     @document = Document.find(params[:id])

    if @document.destroy
      flash[:notice] = "\"#{@document.id}\" was deleted successfully."
      redirect_to documents_index_path
    else
      flash[:error] = "There was an error deleting this result."
      redirect_to documents_index_path
     end
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!
 
   def update
     if current_user.update_attributes(user_params)
       flash[:notice] = "User information updated"
       redirect_to edit_user_registration_path
     else
       flash[:error] = "Invalid user information"
       redirect_to edit_user_registration_path
     end
   end
 
   private
 
   def user_params
     params.require(:user).permit(:name, :avatar)
   end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def analyze
  end
  
  def show 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/search_helper copy 2.rb
module SearchHelper
end

app/helpers/search_helper copy.rb
module SearchHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/documents/_document.html.erb
<% @documents.each do |doc| %>
<h2><%= link_to document.id, document %></h2>
<p><i><%= friendly_date document.created_at %></li></p>
<p><%= document.result %></p>
<p>
	<%= link_to 'Delete', document, method: :delete,
	data: { confirm: 'Are you sure?' } %>
</p>
<% end %>

app/views/documents/entity_tree_map.html.erb
<%= link_to "Return to Index", documents_path %> |
<%= link_to "Return to Result", @document %>
<% json_str = ""
   @entities.each do |entity|
     json_str << '{"text": "' + entity.text + '", "entity_type": "' + entity.entity_type +
        '", "sentiment": "' + entity.sentiment.sentiment_type + '", "mixed": "' + entity.sentiment.sentiment_mixed.to_s +
        '", "relevance": "' + entity.relevance.to_s + '"}, '
   end
   json_str = json_str[0...json_str.length-2]
%>
<style type="text/css">
body {
  overflow: hidden;
  margin: 0;
  font-size: 14px;
  font-family: "Helvetica Neue", Helvetica;
}

#chart, #footer {
  position: absolute;
  top: 0;
}

#footer {
  z-index: 1;
  display: block;
  font-size: 36px;
  font-weight: 300;
  text-shadow: 0 1px 0 #fff;
}

#footer {
    float: right;
    position: relative;
    margin-right: 20px;
    margin-top: 10px;
}

#footer select {
  font-size: 12px;
}

text {
  font-size: 11px;
}

rect {
  fill: none;
  pointer-events: all;
}

.hint {
  position: absolute;
  right: 0;
  width: 100%;
  font-size: 12px;
  color: #999;
}
</style>
<div id="body">
</div>
<div id="footer">
  d3_new.layout.treemap
  <div class="hint">click or option-click to descend or ascend</div>
  <div><select>
    <option value="size">Size</option>
    <option value="count">Count</option>
    </select></div>
</div>
<script type="text/javascript">
  var w = $("div.container").innerWidth - 80,
      h = window.innerHeight - 180,
      x = d3_new.scale.linear().range([0, w]),
      y = d3_new.scale.linear().range([0, h]),
      root,
      node;
  $(window).on('resize', resize);
  function resize() {
    h = window.innerHeight - 180;
    w = $("div.container").width() - 80;
	  x = d3_new.scale.linear().range([0, w]);
	  y = d3_new.scale.linear().range([0, h]);
    $("svg").css('height', h + 'px');
    drawGraph();

  }
  var base_data = [<%= json_str.html_safe %>];

      var flare = {"name": "flare", "children":[
        {"name": "positive", "children":[]}, {"name": "negative", "children":[]},
        {"name": "neutral", "children":[]}, {"name": "mixed", "children":[]}]};

  for(var i=0; i<base_data.length; i++) {
    var obj = base_data[i];
    var type = obj["sentiment"];
    if(obj["mixed"]==1) type = "mixed";
    switch(type){
      case "positive":
        flare["children"][0]["children"].push({"name": obj["text"], "size": obj["relevance"]});
        break;
      case "negative":
        flare["children"][1]["children"].push({"name": obj["text"], "size": obj["relevance"]});
        break;
      case "neutral":
        flare["children"][2]["children"].push({"name": obj["text"], "size": obj["relevance"]});
        break;
      case "mixed":
        flare["children"][3]["children"].push({"name": obj["text"], "size": obj["relevance"]});
        break;
    }
  }
  resize();
  function drawGraph() {
    $('div.chart').remove();
    var treemap = d3_new.layout.treemap()
    .round(false)
    .size([w, h])
    .sticky(true)
    .value(function(d) { return d.size; });

    var svg = d3_new.select("#body").append("div")
    .attr("class", "chart")
    .style("width", w + "px")
    .style("height", h + "px")
    .append("svg:svg")
    .attr("width", w)
    .attr("height", h)
    .append("svg:g")
    .attr("transform", "translate(.5,.5)");
    node = root = flare;

    var nodes = treemap.nodes(root)
    .filter(function(d) { return !d.children; });

    var cell = svg.selectAll("g")
    .data(nodes)
    .enter().append("svg:g")
    .attr("class", "cell")
    .attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; })
    .on("click", function(d) { return zoom(node == d.parent ? root : d.parent, svg); });

    cell.append("svg:rect")
      .attr("width", function(d) { return d.dx - 1; })
      .attr("height", function(d) { return d.dy - 1; })
      .style("fill", function(d) { return color(d.parent.name); });

    cell.append("svg:text")
      .attr("x", function(d) { return d.dx / 2; })
      .attr("y", function(d) { return d.dy / 2; })
      .attr("dy", ".35em")
      .attr("text-anchor", "middle")
      .text(function(d) { return d.name; })
      .style("fill", "#fff")
      .style("opacity", function(d) { d.w = this.getComputedTextLength(); return d.dx > d.w ? 1 : 0.4; });

    d3_new.select(window).on("click", function() { zoom(root, svg); });

    d3_new.select("select").on("change", function() {
      treemap.value(this.value == "size" ? size : count).nodes(root);
      zoom(node, svg);
    });
  }

  function color(d) {
    switch(d) {
      case "positive":
        return "#65C539";
      case "negative":
        return "#C33";
      case "neutral":
        return "#808080";
      case "mixed":
        return "#993366";
    }
  }

  function size(d) {
    return d.size;
  }

  function count(d) {
    return 1;
  }

  function zoom(d, svg) {
    var kx = w / d.dx, ky = h / d.dy;
    x.domain([d.x, d.x + d.dx]);
    y.domain([d.y, d.y + d.dy]);

    var t = svg.selectAll("g.cell").transition()
    .duration(d3_new.event.altKey ? 7500 : 750)
    .attr("transform", function(d) { return "translate(" + x(d.x) + "," + y(d.y) + ")"; });

    t.select("rect")
      .attr("width", function(d) { return kx * d.dx - 1; })
      .attr("height", function(d) { return ky * d.dy - 1; })

    t.select("text")
      .attr("x", function(d) { return kx * d.dx / 2; })
      .attr("y", function(d) { return ky * d.dy / 2; })
      .style("opacity", function(d) { return kx * d.dx > d.w ? 1 : 0.4; });

    node = d;
    d3_new.event.stopPropagation();
  }

</script>
<%= stylesheet_link_tag "d3-process-map/style" %>
<%= stylesheet_link_tag "d3-process-map/svg" %>

app/views/documents/index.html.erb
<h2>Data Store Totals</h2>
<p><b>Total Alchemy API points consumed:</b> <%= Document.sum(:transaction_count) %></p>
<p><b>Number of document analysis returns:</b> <%= Document.count %></p>

<h2>Analysis Results</h2>
<p><%= link_to "Total Relationship Diagram", documents_total_relationship_diagram_path %> |
<%= link_to "Total Knowledge Diagram", documents_total_knowledge_diagram_path %> |
<%= link_to "Total Entity Tree Map", documents_total_entity_tree_map_path %></p>
<HR>
<% @documents.each do |document| %>
  <p><b>Title: </b> <%= link_to document.title, document %></p><button>Relationship Diagram</button>
  <p><b>Author: </b> <%= document.author %></p>
  <p><b>URL: </b> <%= document.url %></p>
	<p><b>Date Retrieved:</b> <%= document.created_at %></p>
  <br/>
  <%= link_to "Relationship Diagram", relationship_diagram_path(document) %> |
  <%= link_to "Knowledge Diagram", knowledge_diagram_path(document) %> |
  <%= link_to "Entity Tree Map", entity_tree_map_path(document) %>
<HR>
<% end %>

app/views/documents/knowledge_diagram.html.erb
<%= link_to "Return to Index", documents_path %> |
<%= link_to "Return to Result", @document %>
<% json_str = ""
   @entities.each do |entity|
     hierarchy = ''
     if entity.knowledge_graph_type_hierarchy.nil?
       hierarchy = ''
     else
       hierarchy = entity.knowledge_graph_type_hierarchy
     end
     json_str << '{"text": "' + entity.text + '", "entity_type": "' + entity.entity_type +
       '", "knowledge_graph_type_hierarchy": "' + hierarchy +
       '", "sentiment": "' + entity.sentiment.sentiment_type + '"}, '
   end
   json_str = json_str[0...json_str.length-2]
%>
<%
relational_entities = "["
@relations.each do |relation|
  if relation.entities.length > 1
    element = "["
    relation.entities.each do |entity|
      element = element + "'" + entity.text + "',"
    end
    element = element[0...element.length-1] + "]"
    relational_entities = relational_entities + element + ","
  end
end
if relational_entities.length > 1
  relational_entities = relational_entities[0...relational_entities.length-1] + "]"
else
  relational_entities = "[]"
end

%>

<div id="split-container">
  <div id="graph-container">
    <div id="graph"></div>
  </div>
</div>
<script>
  var base_data = [<%= json_str.html_safe %>];
  var relational_entities = <%= relational_entities.html_safe %>;
  var config = {
    "graph" : {
      "linkDistance" : 100,
      "charge"       : -400,
      "height"       : 800,
      "numColors"    : 12,
      "labelPadding" : {
        "left"   : 3,
        "right"  : 3,
        "top"    : 2,
        "bottom" : 2
      },
      "labelMargin" : {
        "left"   : 3,
        "right"  : 3,
        "top"    : 2,
        "bottom" : 2
      },
      "ticksWithoutCollisions" : 50
    }
  };
  var data = [];
  data["root"] = {"type":"root", "name":"root", "depends":[], "dependedOnBy":[]};
  for(i=0; i<base_data.length; i++) {
    var obj = base_data[i];
    if(obj["knowledge_graph_type_hierarchy"]==null||obj["knowledge_graph_type_hierarchy"]=="") {
      var node = new Object;
      var str = obj['text'];
      node['type'] = obj['entity_type'];
      node['name'] = str;
      node['sentiment'] = obj['sentiment'];
      node['depends'] = [];
      node['dependedOnBy'] = [];
      data[str] = node;
    } else {
      var hierarchy = obj["knowledge_graph_type_hierarchy"].split("/");
      for(var j=0; j<hierarchy.length-1; j++) {
        var str = hierarchy[j];
        var str1 = ((j+2)==hierarchy.length)?obj['text']:hierarchy[j+1];
        if (str=='')
        {
          str = "root";
        }
        if(str in data) {
          if(data[str]["dependedOnBy"].indexOf(str1)) {
            data[str]["dependedOnBy"][data[str]["dependedOnBy"].length] = str1;
          }
        } else {
          var node = new Object;
          node["type"] = obj['entity_type'];
          node["sentiment"] = obj['sentiment'];
          node["name"] = str;
          node["dependedOnBy"] = [str1];
          node["depends"] = [];
          data[str] = node;
        }
      }

      //					var str = hierarchy[j];
      var str = obj['text'];
      if((str in data)==false) {
        var node = new Object;
        node["type"] = obj['entity_type'];
		    node["sentiment"] = obj['sentiment'];
        node["name"] = str;
        node["dependedOnBy"] = [];
        node["depends"] = [];
        data[str] = node;
      }
    }
  }

  for( node in data ) {
    var depends = data[node]["dependedOnBy"];
    var name = data[node]["name"];
    for(i in depends) {
      str = depends[i];
      if(data[str]["depends"].indexOf(name)==-1) {
        data[str]["depends"][data[str]["depends"].length] = name;
      }
    }
  }
  graph.data = data;
  resize(false);
  drawGraph();
</script>
<%= stylesheet_link_tag "d3-process-map/style" %>
<%= stylesheet_link_tag "d3-process-map/svg" %>

app/views/documents/relationship_diagram.html.erb
<%= link_to "Return to Index", documents_path %> |
<%= link_to "Return to Result", @document %>
<% json_str = ""
   @entities.each do |entity|
     hierarchy = ''
     if entity.knowledge_graph_type_hierarchy.nil?
       hierarchy = ''
     else
       hierarchy = entity.knowledge_graph_type_hierarchy
     end
     json_str << '{"text": "' + entity.text + '", "entity_type": "' + entity.entity_type +
       '", "knowledge_graph_type_hierarchy": "' + hierarchy +
       '", "sentiment": "' + entity.sentiment.sentiment_type + '"}, '
   end
   json_str = json_str[0...json_str.length-2]
%>
<%
relational_entities = "["
@relations.each do |relation|
  if relation.entities.length > 1
    element = "["
    relation.entities.each do |entity|
      element = element + "'" + entity.text + "',"
    end
    element = element[0...element.length-1] + "]"
    relational_entities = relational_entities + element + ","
  end
end
if relational_entities.length > 1
  relational_entities = relational_entities[0...relational_entities.length-1] + "]"
else
  relational_entities = "[]"
end
%>

<div id="split-container">
  <div id="graph-container">
    <div id="graph"></div>
  </div>
</div>
<script>
  var base_data = [<%= json_str.html_safe %>];
  var relational_entities = <%= relational_entities.html_safe %>;
  var config = {
    "graph" : {
      "linkDistance" : 100,
      "charge"       : -400,
      "height"       : 800,
      "numColors"    : 12,
      "labelPadding" : {
        "left"   : 3,
        "right"  : 3,
        "top"    : 2,
        "bottom" : 2
      },
      "labelMargin" : {
        "left"   : 3,
        "right"  : 3,
        "top"    : 2,
        "bottom" : 2
      },
      "ticksWithoutCollisions" : 50
    }
  };
  var data = [];
  for(i=0; i<base_data.length; i++) {
    var obj = base_data[i];
	var str = obj['text'];
	var node = new Object;
	node["type"] = obj['entity_type'];
	node["sentiment"] = obj['sentiment'];
	node["name"] = str;
	node["dependedOnBy"] = [];
	node["depends"] = [];
	data[str] = node;
  }

  for(i=0; i<relational_entities.length; i++) {
	  for(var j=0; j<relational_entities[i].length-1; j++){
		  for(var k=j+1; k<relational_entities[i].length; k++){
			  if((relational_entities[i][j] in data)&&(relational_entities[i][k] in data)) {
				  var str1 = relational_entities[i][j];
				  var str2 = relational_entities[i][k];
				  if(data[str1]["dependedOnBy"].indexOf(str2)==-1) {
					data[str1]["dependedOnBy"][data[str1]["dependedOnBy"].length] = str2;
					data[str1]["depends"][data[str1]["depends"].length] = str2;
				  }
				  if(data[str2]["dependedOnBy"].indexOf(str1)==-1) {
					data[str2]["dependedOnBy"][data[str2]["dependedOnBy"].length] = str1;
					data[str2]["depends"][data[str2]["depends"].length] = str1;
				  }
			  }
		  }
	  }
  }
  graph.data = data;
  resize(false);
  drawGraph();
</script>
<%= stylesheet_link_tag "d3-process-map/style" %>
<%= stylesheet_link_tag "d3-process-map/svg" %>

app/views/documents/search.html.erb
<h2>Content Analysis</h2>

</br>
<%= form_tag("documents/create", method: "get") do %>
	<%= label_tag('type', "Choose your input type:") %>
  </br>

  <div id="text"><%=  radio_button_tag(:type, "text")  %> 
	
    <%=  label_tag(:text_input, "text")  %></div>

	<div id="url"><%=  radio_button_tag(:type, "url")  %>
	
    <%=  label_tag(:url_input, "url")  %></div>
 
  <div id="file"><%=  radio_button_tag(:type, "text")  %>
	
    <%=  label_tag(:file_input, "file")  %></div>
  	
  </br>

  <div id="file_browse"><input type="file" name="inputfile"></div>

  </br>

  <div class="search_field"><%= label_tag(:q, "Perform Analysis:") %></div>
  </br>

  <div class="search_field"><%= search_field_tag :q, value = nil, options = {style:"width:400px;border-radius:5px;padding-bottom:5px;"} %>  
  <%= submit_tag("Analyze") %></div>

<% end %>

app/views/documents/show.html.erb
<div>
  </br>
  <%= link_to "<< Results", documents_path %>
  <h2><%= @document.title %></h2>
  <p>Author:  <%= @document.author %></p>
  <p>Source:  <%= @document.url %></p>
  <p>Sentiment type:  <%= @document.sentiment.sentiment_type %></p>
  <p>Sentiment score:  <%= @document.sentiment.sentiment_score %></p>
  <%= link_to "Relationship Diagram", relationship_diagram_path(@document) %> |
  <%= link_to "Knowledge Diagram", knowledge_diagram_path(@document) %> |
  <%= link_to "Entity Tree Map", entity_tree_map_path(@document) %> |
  <%= link_to "Delete this document", @document, method: :delete, data: {confirm: "Are you sure?"} %>

<HR>
  <h2>Entities: </h2>
  <%= @entities.each do |entity| %>
    <p>Entity: <%= entity.text %></p>
    <p>Count: <%= entity.count %></p>
    <p>Type: <%= entity.entity_type %></p>
    <p>Relevance: <%= entity.relevance %></p>
    <p>Knowledge Graph: <%= entity.knowledge_graph_type_hierarchy %></p>
    <p>Sentiment: <%= entity.sentiment.sentiment_type %></p>
    <p>Sentiment Score: <%= entity.sentiment.sentiment_score %></p>
    <p>Sentiment Mixed: <%= entity.sentiment.sentiment_mixed %></p>
  <HR>
  <% end %>
  <HR>
  <h2>Keywords: </h2>
  <%= @keywords.each do |keyword| %>
    <p>Keyword: <%= keyword.text %></p>
    <p>Type: <%= keyword.keywordable_type %></p>
    <p>Relevance: <%= keyword.relevance %></p>
    <p>Knowledge Graph: <%= keyword.knowledge_graph_type_hierarchy %></p>
    <p>Sentiment: <%= keyword.sentiment.sentiment_type %></p>
    <p>Sentiment Score: <%= keyword.sentiment.sentiment_score %></p>
    <p>Sentiment Mixed: <%= keyword.sentiment.sentiment_mixed %></p>
  <HR>
  <% end %>
  <HR>
  <h2>Concepts: </h2>
  <%= @concepts.each do |concept| %>
    <p>Concept: <%= concept.text %></p>
    <p>Relevance: <%= concept.relevance %></p>
    <p>Knowledge Graph: <%= concept.knowledge_graph_type_hierarchy %></p>
  <HR>
  <% end %>
  <HR>
    <h2>Relations: </h2>
    <%= @relations.each do |relation| %>
    <p>Extracted Sentence: <%= relation.sentence %></p>
    <p>Subject: <%= relation.subject_text %></p>
    <!--put relation loops here (keyword, entity, action, relation object)-->
      <p>Verb Normalization: </p>
      <%= relation.actions.each do |action| %>

        <p>Action: <%= action.text %> </p>
        <p>Lemmatized: <%= action.lemmatized %> </p>
        <p>Verb: <%= action.verb_text %> </p>
        <p>Tense: <%= action.verb_tense %> </p>
      <% end %>
      <%= relation.relation_objects.each do |object| %>
        <p>Object Text:  <%= object.text %> </p>
      <% end %>
    <p>Relational Entities: </p>
    <%= relation.entities.each do |entity| %>
      <p>Entity: <%= entity.text %></p>
      <p>Type: <%= entity.entity_type %></p>
    <% end %>
  <HR>
  <% end %>
  <HR>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Raven</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <ul class="nav nav-tabs">
    <li><%= link_to "Home", root_path %></li>
    <% if current_user %>
      <li><%= link_to "Analyze", search_path %></li>
      <li><%= link_to "Results", documents_path %></li>
    <% end %>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
    
    <div class="pull-right user-info">
      <% if current_user %>
        <%= image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>
           Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>

       <% else %>
         <%= link_to "Sign In", new_user_session_path %> or
         <%= link_to "Sign Up", new_user_registration_path %>
       <% end %>
   </div>
  </ul>
    
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

<%= yield %>
  </div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>About Raven</h1>
</br>
<p>Raven is a text analytics application that allows small businesses to take advantage of the power unstructured data on the web.</p>
</br>
<p>Raven was developed by Joel Ramsey and gustavo Barragan, founders of Glyphex Technologies.</p>

app/views/welcome/analyze.html.erb
<h1>Welcome#analyze</h1>
<p>Find me in app/views/welcome/analyze.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Contact Glyphex</h1>
  <p>General Inquiries</p>
    
      <p><a href="mailto:support@glyphex.com"><i class='glyphicon glyphicon-wrench'></i> Product Support</a></p>
      <p><a href="msilto:info@glyphex.com"><i class='glyphicon glyphicon-bullhorn'></i> Information</a></p>
    

  <p>Joel Ramsey - Co-founder</p>
   
      <p><a href="mailto:joel.d.ramsey@gmail.com"><i class='glyphicon glyphicon-envelope'></i> Email Joel</a></p>
      
    